### ISSUE TITLE
About dependencies when using the devfile outside of an official workshop

### ISSUE THREAD

**Issue by faysou** [mcouliba/cloud-native-workshop#23]
Hello,

I'm trying to use the devfile of this repo on my own openshift home server.

For building the Inventory it built by using 
    env:
      - name: MAVEN_OPTS
        value: '-Xmx2048m -Duser.home=/home/developer'
      - name: MAVEN_MIRROR_URL
        value: https://repo1.maven.org/maven2

but for the Catalog I have difficulties finding the repository that contains the right dependencies (also I don't work with Java usually so I'm not used to find dependencies, I thought using https://maven.repository.redhat.com/ga as MAVEN_MIRROR would solve the problem but I get problems building Inventory that build before).

So my question is would you have a recommendation on which repository to use so I can run your devfile like in a Redhat workshop ? 

I know during the workshop last week in the London Dev Connect Summit it worked, I was there, but I see also that by default the repository used is http://nexus.opentlc-shared.svc:8081/repository/maven-all-public, which means somebody probably prepared a nice private repo so everything worked.

It would be great if the default devfile in github could be configured so it works as well outside of a private maven repo.

Thank you in advance for any help

**Edit**: You seem to have thought about how to setup the workshop with these instructions, but they don't seem to be useable:

An Operator is provided for deploying the workshop infrastructure (lab instructions, Nexus, Gitea, Eclipse Che, etc) on OpenShift.
Please follow the instructions from OpenShift Workshop Operator and deploy the following Workshop custom resource cloud_native_workshop_cr.yaml

**Edit 2**: There seems in fact to be something working here https://github.com/mcouliba/openshift-workshop-operator/tree/ocp4.5

**Edit 3**: The latest version of the workshop is here https://github.com/mcouliba/cloud-native-workshop/blob/demo-mode/devfile.yaml

**Comment by mcouliba** [comment]
Hello @faysou,

About the Maven mirror, just removed the `MAVEN_MIRROR_URL` variable the devfile. All dependencies will be downloaded from Internet instead of a specific repository.

Indeed, there is a Workshop Operator to set up all the component needed for running the workshop. You can find it here https://github.com/mcouliba/workshop-operator. The prerequisite to run this operator is to have an cluster-admin user, the Operator Lifecycle Manager (OLM) available and a set of users as follows `user[1..X]`

Please find below the process to deploy the Workshop Operator:
```
oc login #as administrator
oc new-project workshop-infra
oc apply -f https://raw.githubusercontent.com/mcouliba/workshop-operator/1.3/config/deploy/workshop_operator_deployment.yaml
```
Then apply the ressource `https://raw.githubusercontent.com/mcouliba/workshop-operator/1.3/config/samples/workshop_v1_cloud_native_workshop.yaml` after updating the `spec.users.number` variable

The latest version of the source code of the workshop is here: https://github.com/mcouliba/cloud-native-workshop/tree/5.1

**Comment by faysou** [comment]
Thank you very much for your answer Madou.
I managed to compile by removing the mirror.

I'll try the operator installation later, it's impressive to have an operator for organising worskshops.
